# Generated by Django 5.0.6 on 2024-06-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apifitfood", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nutrition", name="carbohydrate", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="nutrition", name="fat", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="nutrition",
            name="image",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="nutrition", name="name", field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="nutrition", name="proteins", field=models.FloatField(),
        ),
    ]
